import type { Product } from '@/types/product'
import { LOCAL_IMAGES } from '@/lib/images/local-assets'

export const MOCK_PRODUCTS: Product[] = [
  {
    _id: '1',
    name: 'Silk Drape Dress',
    price: 18999,
    description:
      'An ethereal silk drape dress crafted for evening elegance. Fluid silhouette with a refined matte sheen.',
    images: [LOCAL_IMAGES.products.silkDress],
    category: 'dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 12,
    featured: true,
    rating: 4.9,
    discount: 0,
    discountedPrice: 18999,
  },
  {
    _id: '2',
    name: 'Cashmere Blazer',
    price: 24499,
    description:
      'Tailored cashmere blazer with structured shoulders and a soft hand-feel for power dressing.',
    images: [LOCAL_IMAGES.products.cashmereBlazer],
    category: 'best-sellers',
    sizes: ['S', 'M', 'L'],
    stock: 8,
    featured: true,
    rating: 4.8,
    discount: 10,
    discountedPrice: 22049,
  },
  {
    _id: '3',
    name: 'Satin Evening Skirt',
    price: 12999,
    description:
      'High-waist satin skirt with a lustrous finish — perfect for cocktail evenings.',
    images: [LOCAL_IMAGES.products.satinSkirt],
    category: 'dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 15,
    featured: false,
    rating: 4.7,
    discount: 0,
    discountedPrice: 12999,
  },
  {
    _id: '4',
    name: 'Linen Co-ord Set',
    price: 19999,
    description:
      'Breathable linen co-ord set in a relaxed luxury cut for effortless day-to-evening styling.',
    images: [LOCAL_IMAGES.products.linenCoord],
    category: 'co-ord-sets',
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 10,
    featured: true,
    rating: 4.6,
    discount: 15,
    discountedPrice: 16999,
  },
  {
    _id: '5',
    name: 'Embroidered Ethnic Set',
    price: 22999,
    description:
      'Hand-finished embroidery on premium fabric — celebratory ethnic wear with modern tailoring.',
    images: [LOCAL_IMAGES.products.ethnic],
    category: 'ethnic',
    sizes: ['S', 'M', 'L'],
    stock: 6,
    featured: false,
    rating: 4.9,
    discount: 0,
    discountedPrice: 22999,
  },
  {
    _id: '6',
    name: 'Gold Chain Clutch',
    price: 8999,
    description:
      'Minimal gold-tone chain clutch — the finishing touch for evening edits.',
    images: [LOCAL_IMAGES.products.accessories],
    category: 'accessories',
    sizes: ['One Size'],
    stock: 20,
    featured: false,
    rating: 4.5,
    discount: 5,
    discountedPrice: 8549,
  },
]
